backend changes (#17)
* more row data for GameCardsPlayerView

* reorg and improve readme

* move diagrams to a separate readme becuase it's scary

* update for better requirements

* improve scripts and docs

* questionable improvements to bin/mock; breaks sometimes for non-player 1

* fix used port problem for python script

* extract serve.py

* .

---------

Co-authored-by: turk <turk@grackle.club>

diff --git a/bin/sqlc b/bin/sqlc
--- a/bin/sqlc
+++ b/bin/sqlc
@@ -1,11 +1,33 @@
 #!/usr/bin/env bash
 
-printf "Updating sqlc definitions..."
+declare verbose
+case "$1" in
+  -v) verbose="-v" ;;
+  --verbose) verbose="-v" ;;
+  *) verbose="" ;;
+esac
+
+info() {
+  if [ -n "$verbose" ]; then
+	printf "%s" "$1"
+  fi
+}
+error() {
+  echo "error: $1" >&2
+  exit 1
+}
+
+info "Updating sqlc definitions..."
+
+if ! command -v sqlc &> /dev/null; then
+	info "failed.\n"
+	error "sqlc is not installed."
+fi
+
 if ! sqlc generate -f ./db/sqlc.yaml; then
-	printf "failed.\n"
-	echo "Error: sqlc generation"
-	exit 1
+	info "failed.\n"
+	error "sqlc generation"
 else
-	printf "done.\n"
+	info "done.\n"
 fi
 
